
volumes:
  pgdata:

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test123
    volumes:
      - ../pgdb/config:/config
    networks:
      - public_network
      - private_network
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/config/prod.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2028M
        reservations:
          cpus: "0.5"
          memory: 1024M

  flyway:
    container_name: flyway
    build:
      context: ../flyway/
      dockerfile: Dockerfile
    restart: "no"
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/app_db
      FLYWAY_USER: dbadmin
      FLYWAY_PASSWORD: test123
      FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD: "test123"
      FLYWAY_PLACEHOLDERS_APP_READONLY_PASSWORD: "test123"
    networks:
      # - public_network
      - private_network
    depends_on:
      postgres:
        condition: service_healthy
