{
 "title": "Performance Dashboard-Baseline",
 "tags": [
  "aws",
  "baseline",
  "performance test"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/iot-mgnt-telemetry-baseline-alb/24cd8a5e7a24137a"
     },
     "label": "Baseline",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "ECS Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Task Count - FastAPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "label": "Baseline",
     "metricName": "RunningTaskCount",
     "metricQueryType": 1,
     "namespace": "ECS/ContainerInsights",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "RunningTaskCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "iot-mgnt-telemetry-baseline-cluster"
         },
         "property": { "name": "ClusterName", "type": "string" },
         "type": "operator"
        },
        {
         "operator": {
          "name": "=",
          "value": "iot-mgnt-telemetry-baseline-service-fastapi"
         },
         "property": { "name": "ServiceName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(RunningTaskCount) FROM \"ECS/ContainerInsights\" WHERE ClusterName = 'iot-mgnt-telemetry-baseline-cluster' AND ServiceName = 'iot-mgnt-telemetry-baseline-service-fastapi' ORDER BY SUM() ASC",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilization(%) - FastAPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "iot-mgnt-telemetry-baseline-cluster",
      "ServiceName": "iot-mgnt-telemetry-baseline-service-fastapi"
     },
     "label": "Baseline",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Connections - PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-baseline-rds-pgdb"
     },
     "label": "Baseline",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CPU Utilization(%) - PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "iot-mgnt-telemetry-baseline-rds-pgdb"
     },
     "label": "Baseline",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}